### ISSUE TITLE
Update for ESXi 6.5

### ISSUE THREAD

**Issue by TheOttoman2012** [rlakey/vmware-stig-powercli#1]
Now that the stig for 6.5 has been released, were you considering on updating or releasing a script for 6.5, or is this project officially dead?

**Comment by equinelady** [comment]
IDK, I don't work on the project anymore.




 

    On Wednesday, September 18, 2019, 6:37:54 PM EDT, TheOttoman2012 <notifications@github.com> wrote:  
 
 
Now that the stig for 6.5 has been released, were you considering on updating or releasing a script for 6.5, or is this project officially dead?

**Comment by VIKing91107** [comment]
Would be greatly appreciated if you continued. :) your scripts are second to none and have really (outside of a little bit of polishing for our environments, to be expected) saved me and my team a ton of time!

**Comment by rlakey** [comment]
Please see this repo for newer content.

https://github.com/vmware/dod-compliance-and-automation
